-- CreateTable
CREATE TABLE "regulations" (
    "id" INTEGER NOT NULL,
    "origin_name" TEXT,
    "destination_name" TEXT,
    "origin_address" TEXT,
    "destination_address" TEXT,
    "origin_sector" TEXT,
    "destination_sector" TEXT,
    "patient_name" TEXT,
    "patient_age" TEXT,
    "patient_sex" TEXT,
    "birth_date" TEXT,
    "weight_kg" DOUBLE PRECISION,
    "height_cm" TEXT,
    "diagnosis" TEXT,
    "call_reason" TEXT,
    "patient_type" TEXT,
    "patient_type_other" TEXT,
    "companion" TEXT,
    "is_intubated" BOOLEAN,
    "is_obese" BOOLEAN,
    "triage_completed" BOOLEAN,
    "health_plan" TEXT,
    "procedure" TEXT,
    "equipment" TEXT,
    "device_usage" TEXT,
    "origin_doctor" TEXT,
    "destination_doctor" TEXT,
    "notes" TEXT,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "regulations_pkey" PRIMARY KEY ("id")
);
